config:
  dirs:
    cfg_path: /home/dmifsud/Projects/NDT-U/configs/t11_piano.yaml
    dataset_dir: /home/dmifsud/Projects/NDT-U/data/t11_piano
    raw_data_dir: /snel/share/data/braingate/T11/T11PianoSessions