method: grid
name: factor_dim_pos_emb_sweep
program : train.py
command: ['${env}', 'python3', '${program}', '-y', '--silent']
parameters:
  model.factor_dim:
    values: [16, 32, 64, 128]
  model.pos_emb_size:
    values: [8, 16, 32, 64, 128, 256]
  
